spring:
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: false

google:
  workspace:
    credentials-file-path: "classpath:credentials.json"
    sheets:
      spreadsheet-id: "1JWMj6GHsVXOCDttZuOQqNe6JdmNtXo3PAEGzaSeMe4s"